{% set name = "Benchmark-4dn" %}
{% set version = "0.5.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dfb0a542452f2aecc3bd306550246b6c0783acffacd855501d25a34366b69c1a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - Benchmark

about:
  home: "https://github.com/SooLee/Benchmark/"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "Benchmark functions that returns total space, mem, cpu given input size and parameters for the CWL workflows"
  doc_url: "https://github.com/SooLee/Benchmark"

extra:
  recipe-maintainers:
    - soolee
